/**
 * Curated deals dataset — manually maintained from known registrar promotions.
 * Updated periodically. Always available as fallback when live scrapers fail.
 */
import type { DomainDeal } from "../types";

const NOW = new Date().toISOString();

export const CURATED_DEALS: DomainDeal[] = [
  // ─── CLOUDFLARE (at-cost, no markup) ───────────────────────────────────────
  {
    id: "cf-com",
    tld: ".com",
    registrar: "Cloudflare",
    registrarUrl: "https://www.cloudflare.com/products/registrar/",
    dealUrl: "https://www.cloudflare.com/products/registrar/",
    regularPrice: 10.44,
    salePrice: 9.15,
    discount: 12,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "At-cost pricing every year, no markup ever",
    lastUpdated: NOW,
    source: "cloudflare",
    featured: true,
    tags: ["at-cost", "no-markup", "cloudflare", "popular"],
  },
  {
    id: "cf-net",
    tld: ".net",
    registrar: "Cloudflare",
    registrarUrl: "https://www.cloudflare.com/products/registrar/",
    dealUrl: "https://www.cloudflare.com/products/registrar/",
    regularPrice: 11.5,
    salePrice: 9.77,
    discount: 15,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "At-cost pricing, no markup",
    lastUpdated: NOW,
    source: "cloudflare",
    featured: true,
    tags: ["at-cost", "cloudflare", "popular"],
  },
  {
    id: "cf-org",
    tld: ".org",
    registrar: "Cloudflare",
    registrarUrl: "https://www.cloudflare.com/products/registrar/",
    dealUrl: "https://www.cloudflare.com/products/registrar/",
    regularPrice: 11.5,
    salePrice: 9.93,
    discount: 14,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "At-cost pricing, no markup",
    lastUpdated: NOW,
    source: "cloudflare",
    featured: false,
    tags: ["at-cost", "cloudflare"],
  },
  {
    id: "cf-dev",
    tld: ".dev",
    registrar: "Cloudflare",
    registrarUrl: "https://www.cloudflare.com/products/registrar/",
    dealUrl: "https://www.cloudflare.com/products/registrar/",
    regularPrice: 14.0,
    salePrice: 12.14,
    discount: 13,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "At-cost pricing, perfect for developers",
    lastUpdated: NOW,
    source: "cloudflare",
    featured: true,
    tags: ["at-cost", "cloudflare", "developer"],
  },
  {
    id: "cf-app",
    tld: ".app",
    registrar: "Cloudflare",
    registrarUrl: "https://www.cloudflare.com/products/registrar/",
    dealUrl: "https://www.cloudflare.com/products/registrar/",
    regularPrice: 17.0,
    salePrice: 14.0,
    discount: 18,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "At-cost pricing",
    lastUpdated: NOW,
    source: "cloudflare",
    featured: false,
    tags: ["at-cost", "cloudflare"],
  },

  // ─── NAMECHEAP PROMOS ───────────────────────────────────────────────────────
  {
    id: "nc-xyz-promo",
    tld: ".xyz",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.xyz",
    regularPrice: 13.98,
    salePrice: 0.99,
    discount: 93,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Renewal at $13.98/yr",
    lastUpdated: NOW,
    source: "namecheap",
    featured: true,
    tags: ["first-year", "namecheap", "new-gtld"],
  },
  {
    id: "nc-site-promo",
    tld: ".site",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.site",
    regularPrice: 17.98,
    salePrice: 1.98,
    discount: 89,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Renewal at $17.98/yr",
    lastUpdated: NOW,
    source: "namecheap",
    featured: false,
    tags: ["first-year", "namecheap", "new-gtld"],
  },
  {
    id: "nc-online-promo",
    tld: ".online",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.online",
    regularPrice: 29.98,
    salePrice: 1.98,
    discount: 93,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Renewal at $29.98/yr",
    lastUpdated: NOW,
    source: "namecheap",
    featured: false,
    tags: ["first-year", "namecheap", "new-gtld"],
  },
  {
    id: "nc-store-promo",
    tld: ".store",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.store",
    regularPrice: 49.98,
    salePrice: 2.98,
    discount: 94,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Great for eCommerce. Renewal at $49.98/yr",
    lastUpdated: NOW,
    source: "namecheap",
    featured: true,
    tags: ["first-year", "namecheap", "ecommerce"],
  },
  {
    id: "nc-tech-promo",
    tld: ".tech",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.tech",
    regularPrice: 49.98,
    salePrice: 4.98,
    discount: 90,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Perfect for tech startups. Renewal at $49.98/yr",
    lastUpdated: NOW,
    source: "namecheap",
    featured: true,
    tags: ["first-year", "namecheap", "tech", "startup"],
  },
  {
    id: "nc-club-promo",
    tld: ".club",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.club",
    regularPrice: 8.48,
    salePrice: 0.99,
    discount: 88,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo",
    lastUpdated: NOW,
    source: "namecheap",
    featured: false,
    tags: ["first-year", "namecheap", "community"],
  },
  {
    id: "nc-info-promo",
    tld: ".info",
    registrar: "Namecheap",
    registrarUrl: "https://www.namecheap.com",
    dealUrl: "https://www.namecheap.com/domains/registration/results/?domain=.info",
    regularPrice: 15.98,
    salePrice: 1.98,
    discount: 88,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo",
    lastUpdated: NOW,
    source: "namecheap",
    featured: false,
    tags: ["first-year", "namecheap"],
  },

  // ─── HOSTINGER (free with hosting) ─────────────────────────────────────────
  {
    id: "hostinger-free-com",
    tld: ".com",
    registrar: "Hostinger",
    registrarUrl: "https://www.hostinger.com",
    dealUrl: "https://www.hostinger.com/web-hosting",
    regularPrice: 12.0,
    salePrice: 0,
    discount: 100,
    dealType: "bundle",
    firstYearOnly: true,
    validUntil: null,
    notes: "Free .com with any hosting plan (from $2.99/mo). Requires hosting purchase.",
    lastUpdated: NOW,
    source: "hostinger",
    featured: true,
    tags: ["free", "bundle", "hosting", "hostinger"],
  },
  {
    id: "hostinger-com-promo",
    tld: ".com",
    registrar: "Hostinger",
    registrarUrl: "https://www.hostinger.com",
    dealUrl: "https://www.hostinger.com/domain-name-search",
    regularPrice: 12.0,
    salePrice: 0.99,
    discount: 92,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo for standalone registration",
    lastUpdated: NOW,
    source: "hostinger",
    featured: true,
    tags: ["first-year", "hostinger", "popular"],
  },

  // ─── GODADDY PROMOS ─────────────────────────────────────────────────────────
  {
    id: "gd-com-promo",
    tld: ".com",
    registrar: "GoDaddy",
    registrarUrl: "https://www.godaddy.com",
    dealUrl: "https://www.godaddy.com/domains/domain-name-search",
    regularPrice: 19.99,
    salePrice: 0.99,
    discount: 95,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year only for new customers. Renewal at $19.99/yr",
    lastUpdated: NOW,
    source: "godaddy",
    featured: true,
    tags: ["first-year", "godaddy", "popular", "new-customer"],
  },
  {
    id: "gd-us",
    tld: ".us",
    registrar: "GoDaddy",
    registrarUrl: "https://www.godaddy.com",
    dealUrl: "https://www.godaddy.com/tlds/us-domain",
    regularPrice: 4.99,
    salePrice: 2.99,
    discount: 40,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "Cheap everyday price",
    lastUpdated: NOW,
    source: "godaddy",
    featured: false,
    tags: ["cheap", "godaddy", "country-code"],
  },

  // ─── IONOS / 1&1 ───────────────────────────────────────────────────────────
  {
    id: "ionos-com-promo",
    tld: ".com",
    registrar: "IONOS",
    registrarUrl: "https://www.ionos.com",
    dealUrl: "https://www.ionos.com/domains/com-domain",
    regularPrice: 15.0,
    salePrice: 1.0,
    discount: 93,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year $1 deal. Renewal at standard price.",
    lastUpdated: NOW,
    source: "ionos",
    featured: true,
    tags: ["first-year", "ionos", "popular"],
  },

  // ─── DYNADOT ───────────────────────────────────────────────────────────────
  {
    id: "dynadot-ai",
    tld: ".ai",
    registrar: "Dynadot",
    registrarUrl: "https://www.dynadot.com",
    dealUrl: "https://www.dynadot.com/domain/tld.html?tld=ai",
    regularPrice: 49.99,
    salePrice: 33.99,
    discount: 32,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "Competitive .ai pricing. Very popular for AI startups.",
    lastUpdated: NOW,
    source: "dynadot",
    featured: true,
    tags: ["ai", "startup", "popular", "dynadot"],
  },
  {
    id: "dynadot-co",
    tld: ".co",
    registrar: "Dynadot",
    registrarUrl: "https://www.dynadot.com",
    dealUrl: "https://www.dynadot.com/domain/tld.html?tld=co",
    regularPrice: 29.99,
    salePrice: 9.99,
    discount: 67,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "Competitive everyday .co pricing",
    lastUpdated: NOW,
    source: "dynadot",
    featured: false,
    tags: ["startup", "popular", "dynadot"],
  },

  // ─── FREE / STUDENT PROGRAMS ────────────────────────────────────────────────
  {
    id: "github-student-me",
    tld: ".me",
    registrar: "GitHub Education",
    registrarUrl: "https://education.github.com",
    dealUrl: "https://education.github.com/pack",
    regularPrice: 19.99,
    salePrice: 0,
    discount: 100,
    dealType: "free",
    firstYearOnly: true,
    validUntil: null,
    notes: "Free via GitHub Student Developer Pack. Requires student verification.",
    lastUpdated: NOW,
    source: "curated",
    featured: true,
    tags: ["free", "student", "education", "github"],
  },
  {
    id: "github-student-name",
    tld: ".name",
    registrar: "GitHub Education",
    registrarUrl: "https://education.github.com",
    dealUrl: "https://education.github.com/pack",
    regularPrice: 9.99,
    salePrice: 0,
    discount: 100,
    dealType: "free",
    firstYearOnly: true,
    validUntil: null,
    notes: "Free via GitHub Student Developer Pack. Requires student verification.",
    lastUpdated: NOW,
    source: "curated",
    featured: false,
    tags: ["free", "student", "education", "github"],
  },
  {
    id: "freenom-tk",
    tld: ".tk",
    registrar: "Freenom",
    registrarUrl: "https://www.freenom.com",
    dealUrl: "https://www.freenom.com",
    regularPrice: 0,
    salePrice: 0,
    discount: 100,
    dealType: "free",
    firstYearOnly: false,
    validUntil: null,
    notes: "Free for up to 1 year (renewable). Service availability may vary.",
    lastUpdated: NOW,
    source: "curated",
    featured: false,
    tags: ["free", "freenom", "ccTLD"],
  },
  {
    id: "freenom-ml",
    tld: ".ml",
    registrar: "Freenom",
    registrarUrl: "https://www.freenom.com",
    dealUrl: "https://www.freenom.com",
    regularPrice: 0,
    salePrice: 0,
    discount: 100,
    dealType: "free",
    firstYearOnly: false,
    validUntil: null,
    notes: "Free for up to 1 year (renewable). Service availability may vary.",
    lastUpdated: NOW,
    source: "curated",
    featured: false,
    tags: ["free", "freenom", "ccTLD"],
  },
  {
    id: "freenom-ga",
    tld: ".ga",
    registrar: "Freenom",
    registrarUrl: "https://www.freenom.com",
    dealUrl: "https://www.freenom.com",
    regularPrice: 0,
    salePrice: 0,
    discount: 100,
    dealType: "free",
    firstYearOnly: false,
    validUntil: null,
    notes: "Free for up to 1 year (renewable). Service availability may vary.",
    lastUpdated: NOW,
    source: "curated",
    featured: false,
    tags: ["free", "freenom", "ccTLD"],
  },

  // ─── PORKBUN EVERYDAY CHEAP ────────────────────────────────────────────────
  {
    id: "pb-xyz",
    tld: ".xyz",
    registrar: "Porkbun",
    registrarUrl: "https://porkbun.com",
    dealUrl: "https://porkbun.com/tld/xyz",
    regularPrice: 13.06,
    salePrice: 1.99,
    discount: 85,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Renewal at $13.06/yr",
    lastUpdated: NOW,
    source: "porkbun-api",
    featured: true,
    tags: ["promo", "porkbun", "new-gtld", "popular"],
  },
  {
    id: "pb-me",
    tld: ".me",
    registrar: "Porkbun",
    registrarUrl: "https://porkbun.com",
    dealUrl: "https://porkbun.com/tld/me",
    regularPrice: 22.88,
    salePrice: 5.49,
    discount: 76,
    dealType: "promo",
    firstYearOnly: true,
    validUntil: null,
    notes: "First-year promo. Great for personal brands.",
    lastUpdated: NOW,
    source: "porkbun-api",
    featured: true,
    tags: ["promo", "porkbun", "personal"],
  },
  {
    id: "pb-io",
    tld: ".io",
    registrar: "Porkbun",
    registrarUrl: "https://porkbun.com",
    dealUrl: "https://porkbun.com/tld/io",
    regularPrice: 34.98,
    salePrice: 26.99,
    discount: 23,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "Everyday competitive .io price",
    lastUpdated: NOW,
    source: "porkbun-api",
    featured: true,
    tags: ["startup", "porkbun", "popular"],
  },
  {
    id: "pb-app",
    tld: ".app",
    registrar: "Porkbun",
    registrarUrl: "https://porkbun.com",
    dealUrl: "https://porkbun.com/tld/app",
    regularPrice: 20.38,
    salePrice: 14.06,
    discount: 31,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "HTTPS required for .app domains",
    lastUpdated: NOW,
    source: "porkbun-api",
    featured: false,
    tags: ["developer", "porkbun"],
  },
  {
    id: "pb-sh",
    tld: ".sh",
    registrar: "Porkbun",
    registrarUrl: "https://porkbun.com",
    dealUrl: "https://porkbun.com/tld/sh",
    regularPrice: 26.78,
    salePrice: 19.38,
    discount: 28,
    dealType: "sale",
    firstYearOnly: false,
    validUntil: null,
    notes: "Popular for CLI tools and developer projects",
    lastUpdated: NOW,
    source: "porkbun-api",
    featured: false,
    tags: ["developer", "porkbun"],
  },
];

export function getCuratedDeals(): DomainDeal[] {
  return CURATED_DEALS;
}
